CREATE TABLE Roles
(
	RoleID INT PRIMARY KEY IDENTITY(1,1),
	RoleName VARCHAR(50) NOT NULL,
	Description VARCHAR(200),
);
 CREATE TABLE Departments
 (
	DeptID INT PRIMARY KEY IDENTITY(1,1),
	DeptName VARCHAR(100) NOT NULL,
	Location VARCHAR(100),
	CreateOn DATETIME DEFAULT GETDATE()
);

 CREATE TABLE Users
 (
	UserID INT PRIMARY KEY IDENTITY(1,1),
	Username VARCHAR(100) NOT NULL,
	PasswordHash VARCHAR(255) NOT NULL,
	RoleID INT NOT NULL,
	IsActive BIT DEFAULT 1,
	CreateOn DATETIME DEFAULT GETDATE()
);

 CREATE TABLE Employees
 (
	EmpID INT PRIMARY KEY IDENTITY(1,1),
	FullName VARCHAR(100) NOT NULL,
	Gender VARCHAR(10),
	DOB DATE,
	Address VARCHAR(255),
	Phone VARCHAR(255),
	Email VARCHAR(100),
	DeptID INT,
	UserID INT,
	JoinDate DATE,
	Salary Decimal(10,2),
	IsActive BIT DEFAULT 1
);

 CREATE TABLE Documents
 (
	DocID INT PRIMARY KEY IDENTITY(1,1),
	DocType VARCHAR(100),
	FileName VARCHAR(255),
	FilePath VARCHAR(500),
	UploadDate DATETIME DEFAULT GETDATE()
);